//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessWithData
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersTable
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string gender { get; set; }
        public string resident { get; set; }
        public Nullable<long> privateId { get; set; }
        public Nullable<System.DateTime> dateOfRegistration { get; set; }
        public string registrationIp { get; set; }
        public string userLanguage { get; set; }
        public string mail { get; set; }
        public Nullable<long> mobile { get; set; }
        public string userPassword { get; set; }
        public string country { get; set; }
        public string regionState { get; set; }
        public string city { get; set; }
        public string addressOne { get; set; }
        public string addressTwo { get; set; }
        public string postalCode { get; set; }
    }
}
